<?php
namespace Thainph\Filemanager;

use App\Http\Middleware\EncryptCookies;
use App\Http\Middleware\VerifyCsrfToken;
use Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse;
use Illuminate\Routing\Middleware\SubstituteBindings;
use Illuminate\Session\Middleware\StartSession;
use Illuminate\Support\ServiceProvider;
use Illuminate\View\Middleware\ShareErrorsFromSession;
use Thainph\Filemanager\Middlewares\FileManagerMimeMiddleware;
use Thainph\Filemanager\Middlewares\FileManagerCorsMiddleware;
use Illuminate\Routing\Router;

class FileManagerServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->publishes([
            __DIR__.'/config/file-manager.php' => config_path('file-manager.php'),
        ], 'file-manager-config');
        $this->publishes([
            __DIR__.'/assets' => public_path('vendor/file-manager'),
        ], 'file-manager-assets');

        $this->loadRoutesFrom(__DIR__.'/routes/web.php');
        $this->loadViewsFrom(__DIR__.'/Resources/views', 'file-manager');
        $this->loadTranslationsFrom(__DIR__.'/Resources/lang', 'file-manager');

        $router = $this->app->make(Router::class);
        $router->aliasMiddleware('file_manager_mimes', FileManagerMimeMiddleware::class);
        $router->aliasMiddleware('file_manager_cors', FileManagerCorsMiddleware::class);
        $router->aliasMiddleware('file_manager_encrypt_cookies', EncryptCookies::class);
        $router->aliasMiddleware('file_manager_queued_cookies', AddQueuedCookiesToResponse::class);
        $router->aliasMiddleware('file_manager_start_session', StartSession::class);
        $router->aliasMiddleware('file_manager_share_session_errors', ShareErrorsFromSession::class);
        $router->aliasMiddleware('file_manager_substitute_bindings',   SubstituteBindings::class);
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
